
#define BUILD_WIN32 1
#define HAVE_WINDOWS_H 1
#define HAVE_ASSERT_H 1
#define HAVE_CTYPE_H 1
#define HAVE_LIMITS_H 1
#define HAVE_LOCALE_H 1
#define HAVE_MATH_H 1
#define HAVE_STDARG_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_PHYSFS_H 1
#define HAVE_EXPAT_H 1
#define HAVE_CAIRO_CAIRO_H 1
#define HAVE_FT2BUILD_H 1